package com.locapeer.messaging

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Wire format for circle (group) messages. A group message is an ordinary NIP-44 encrypted DM
 * (kind ENCRYPTED_DM) whose decrypted plaintext is this envelope, distinguished from a plain
 * text message by a leading control-character [MAGIC]. Plain 1:1 messages stay raw text, so
 * older clients and the existing link/pin detection keep working untouched.
 *
 * The envelope carries the circle id, its current name and full member list, so a recipient can
 * materialise the same circle locally without a separate group-invite handshake. Each recipient
 * gets their own individually encrypted copy - there is no shared group key.
 */
@Serializable
data class GroupMessage(
    /** Stable circle id (UUID) generated by whoever created the circle. */
    val gid: String,
    /** Circle display name at send time (applied by a recipient only on first materialisation). */
    val gname: String,
    /** Full member list as pubkeys, including the sender, so recipients can reconstruct the circle. */
    val members: List<String>,
    /** Message body. A location share is just a body containing the OpenStreetMap mlat/mlon URL. */
    val text: String
)

object GroupWire {
    /** Control char + tag. A user cannot type U+0001 on a keyboard, so this can't collide with real text. */
    private const val MAGIC = "LPG1"

    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }

    fun encode(message: GroupMessage): String = MAGIC + json.encodeToString(GroupMessage.serializer(), message)

    /** Returns the decoded group message, or null when [plaintext] is an ordinary 1:1 text message. */
    fun decode(plaintext: String): GroupMessage? {
        if (!plaintext.startsWith(MAGIC)) return null
        return try {
            json.decodeFromString(GroupMessage.serializer(), plaintext.substring(MAGIC.length))
        } catch (e: Exception) {
            null
        }
    }
}
