package com.locapeer.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * A "circle" (a.k.a. group) is a purely client-side grouping of existing contacts. It has no
 * shared key and no server-side representation: sharing a location or a message with a circle
 * fans out one individually NIP-44-encrypted event per member, so the E2E model is unchanged.
 *
 * The [id] is a stable UUID generated by whoever creates the circle. Every group message carries
 * that id plus the current member list, so a recipient can materialise the same circle locally
 * without a separate group-invite handshake (see HeartbeatReceiver group handling).
 */
@Entity(tableName = "circles")
data class CircleEntity(
    @PrimaryKey val id: String,
    val name: String,
    val createdAt: Long = System.currentTimeMillis()
)
